#+Title: text

* Was ist modulare Arithmetik?

Die Modulare Arithmetik beruht darauf, das man sich eine Primzahl sucht und mit
dieser Zahl und einer Zahlenmenge von dieser Zahl - 1. Ich werde in den
folgenden Teilen diese Zahl m nennen. Die grosse Frage ist ja aber, was ist
modulo.

* Was ist modulo rechnen

Modulo rechenen beschreibt das Rechnen mit Resten. So Wird beim dividieren einer
Zahl keine Kommastellen angefangen sondern einfach der Rest Notiert. Dies ist
auch das Resultat einer Modulo Rechnung.

Die Notation einer modulo Rechnung wird in Programmiersprache mit einem Prozent
zeichen angegeben. Beispiel: 7 % 3 = 1 <br>
Die Notation in der Mathematik ist sehr àhnlich. Beispiel: 8mod3 = 2. Allerdings
wird das Gleichheitszeichen häufig durch ein Kongruenzzeichen ersetzt. Die
Schreibweise ist eigentlich ein Gleichheitszeichen, mit dem Unterschied, das es
aus drei Strichen besteht.

* Was kann man nun damit machen?

Wir nehemen eine Primzahl m die möglichst gross ist, damit es viele Möglichkeiten
gibt. Anschliessend definiert man eine Zahlenmengen Zm die von null bis m-1
geht. Anschliessend suchen wir eine Zahl x die möglichst viele Resultate
produziert. Die Grösste Zahl die x sein kann ist m/2-1.

* Wieso sind modulo Primzahlen intersssant für die Verschlüsslung

Wenn man die Nachricht mit dem Schlüssel entschlüsselt, und das ganze im
Binärsystem macht, ist man spätestens nach 2r Multiplikationen fertog, wobei r
die Anzahl der Binärziffern ist. Das Interessante das ganze im Binärsystem zu
machen ist, das man die Quadrierungen zu Multiplikationen umwandeln kann.

* Was ist ein Generator?

Der Generator ist die Zahl die deren alle Reste von Modulo abdecken.

* Wie Funktioniert Diffie-Hellmann schematisch?

* Wieso ist es einfacher hochzurechenen als logarithmen zu berechnen?

* Wie Funktioniert die El Gamal verschlüsselung

* Wieso ist RSA einfacher?


|                    | Alice   | Eve         | Bob     | Inventar Alice     | Inventar Eve   | Inventar Bob             |
|--------------------+---------+-------------+---------+--------------------+----------------+--------------------------|
| publik uebertragen | g,p     | --- g,p --> | g,p     | g, p               | g, p           | g, p                     |
| privat generiert   | a       |             | b       | g, p, a            | g, p           | g, p, b                  |
| berechnen          | g^a     |             | g^b     | g, p, a / g^a      | g, p           | g, p, b / g^b            |
| publik uebertragen | g^a     | --- g^a --> | g^a     | g, p, a / g^a      | g, p, g^a      | g, p, a, g^a / g^b       |
| publik uebertragen | g^b     | <-- g^b --- | g^b     | g, p, a, g^b / g^a | g, p, g^a, g^b | g, p, a, g^a / g^b       |
| berechnen          | (g^b)^a |             | (g^a)^b | g, p, a, g^b, g^ba | g, p, g^a, g^b | g, p, a, g^a, g^ab / g^b |
